Repository Quansight-Labs/jupyterlab-accessible-themes, pull requests merged in 2023-07, with the labels that each got.

#64 Update JupyterLab version in README.md
  README.md
Labels: type: maintenance 🛠

#63 MAINT - Miscellaneous maintenance tasks
  .github/workflows/add-pr-to-project.yml
  .github/workflows/binder-on-pr.yml
  .github/workflows/check-links.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  RELEASE.md
  jupyterlab_accessible_themes/__init__.py
  lerna.json
  packages/githublight/README.md
  packages/githublight/src/index.ts
  packages/githublight/style/index.css
  packages/githublight/style/variables.css
  packages/pitayasmoothie/README.md
  packages/pitayasmoothie/src/index.ts
  packages/pitayasmoothie/style/index.css
  packages/pitayasmoothie/style/variables.css
  pyproject.toml
  setup.py
  ui-tests/tests/jupyterlab_accessible_themes.spec.ts
Labels: type: maintenance 🛠, area: CI 👷🏽‍♀️, area: dependencies 📦

#61 Fix schema error
  .github/workflows/check-links.yml
  README.md
  lerna.json
  package.json
  packages/githublight/src/index.ts
  packages/pitayasmoothie/src/index.ts
  schema/plugin.json
Labels: type: bug 🐛, status: done ✅

#65 ENH - Replace binder on PR workflow
  .github/workflows/binder-on-pr.yml
Labels: type: enhancement 💅🏼, area: CI 👷🏽‍♀️

#62 Fix Github Light and Pitaya Smoothie contrast color bugs
  packages/githublight/style/index.css
  packages/githublight/style/variables.css
  packages/pitayasmoothie/style/variables.css
Labels: type: bug 🐛, needs: review 👀

#67 Update pyproject.toml and readme
  README.md
  pyproject.toml
Labels: type: bug 🐛
